### ISSUE TITLE
Selecting a subdirectory that does not exist break Iceberg

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#273] opened 2017-02-06 09:05 UTC
I wanted to initialize a new project and to add sources in a sub-directory called `src` but I got a RSOD since the directory does not exist.

How I got the problem:
- I created a new repo on github
- I cloned it on my disk
- I opened an image and loaded Iceberg
- I clicked on `Add local repository`
- I selected the folder and added `src` as subrepo

Since I do not have any package yet, the sub directory does not exist. Iceberg expect a sub directory, so I got this: https://puu.sh/tQCl3/773d1d6abb.png

Possible correction:
- At the repository creation in Iceberg, check that the directory exist. If it does not exist open a window to ask to the user if he wants to init the subdirectory or if it is a mistake. If it is a mistake, reopen the repository initialization window.

**Comment by estebanlm** [comment] 2017-02-06 09:15
this is a duplicate of issue #257

**Closed by estebanlm** 2017-02-06 09:15 UTC
Labels: duplicate
